import React, { useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Sparkles, Film, UserRound, Users, Bell, Search, Heart, MessageCircle, Send, Check, MapPin, Plus, LogOut, Award, Menu, X } from 'lucide-react'
import './styles.css'

const regions = ['Bollywood', 'Tollywood', 'Kollywood', 'Mollywood', 'Sandalwood']
const roles = ['Actor', 'Director', 'Writer', 'Producer', 'Cinematographer', 'Editor', 'Composer']
const seedPosts = [
 { id: 1, name: 'Aarav Mehta', role: 'Director', region: 'Bollywood', time: '2h', avatar: 'AM', content: 'Wrapped our final day on set! The magic happens because of every single person behind the frame. Here’s to new stories and brave beginnings. 🎬', likes: 48, comments: 6, liked: false },
 { id: 2, name: 'Nandini Rao', role: 'Actor', region: 'Tollywood', time: '5h', avatar: 'NR', content: 'Looking to connect with passionate costume designers and movement artists for an upcoming period drama. Let’s make something beautiful together.', likes: 32, comments: 12, liked: false },
]
const people = [{ name: 'Kabir Khan', role: 'Producer', region: 'Bollywood', avatar: 'KK' }, { name: 'Meera Nair', role: 'Writer', region: 'Mollywood', avatar: 'MN' }, { name: 'Vikram Iyer', role: 'Cinematographer', region: 'Kollywood', avatar: 'VI' }]

function Avatar({ initials, large=false }) { return <div className={`avatar ${large ? 'large' : ''}`}>{initials}</div> }
function Toast({ text }) { return <div className="toast"><Sparkles size={16}/>{text}</div> }
function App() {
 const [onboarded, setOnboarded] = useState(localStorage.getItem('cinema-onboarded') === 'yes')
 const [region, setRegion] = useState('Bollywood'); const [role, setRole] = useState('Actor'); const [name, setName] = useState('Ananya Sharma')
 const [tab, setTab] = useState('home'); const [posts, setPosts] = useState(seedPosts); const [composer, setComposer] = useState(''); const [toast, setToast] = useState(''); const [search, setSearch] = useState(''); const [menu, setMenu] = useState(false)
 const notify = text => { setToast(text); setTimeout(() => setToast(''), 2200) }
 const finish = () => { localStorage.setItem('cinema-onboarded','yes'); setOnboarded(true); notify('Welcome to your new creative network!') }
 const like = id => { setPosts(posts.map(p => p.id === id ? {...p, liked: !p.liked, likes: p.likes + (p.liked ? -1 : 1)} : p)); notify('A little love sent ✨') }
 const publish = () => { if (!composer.trim()) return; setPosts([{ id: Date.now(), name, role, region, time: 'now', avatar: 'AS', content: composer, likes: 0, comments: 0, liked: false }, ...posts]); setComposer(''); notify('Your story is live! 🎬') }
 if (!onboarded) return <Onboarding region={region} setRegion={setRegion} role={role} setRole={setRole} name={name} setName={setName} finish={finish}/>
 return <div className="app"><header className="topbar"><div className="brand" onClick={() => setTab('home')}><span className="brand-mark">✦</span><span>INDIAN <b>CINEMA</b></span></div><div className="search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find your next collaborator..."/></div><div className="top-actions"><button className="icon-btn"><Bell size={20}/><i/></button><Avatar initials="AS"/><button className="menu-toggle" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
 <div className={`layout ${menu?'open':''}`}><aside className="sidebar"><div className="profile-mini"><Avatar initials="AS" large/><div><strong>{name}</strong><span>{role} · {region}</span></div></div><nav>{[['home',Film,'My Studio'],['network',Users,'My Network'],['profile',UserRound,'My Profile']].map(([key,Icon,label])=><button className={tab===key?'active':''} onClick={()=>{setTab(key);setMenu(false)}} key={key}><Icon size={19}/>{label}</button>)}</nav><div className="side-card"><Award size={22}/><strong>Keep creating</strong><span>Complete your profile to unlock your first badge.</span><div className="progress"><b/></div></div><button className="logout" onClick={()=>{localStorage.removeItem('cinema-onboarded');setOnboarded(false)}}><LogOut size={17}/>Sign out</button></aside>
 <main className="main">{tab==='home' && <Home name={name} role={role} region={region} posts={posts} composer={composer} setComposer={setComposer} publish={publish} like={like} notify={notify}/>} {tab==='network' && <Network search={search} notify={notify}/>} {tab==='profile' && <Profile name={name} role={role} region={region} notify={notify}/>}</main><aside className="rightbar"><div className="set-card"><div className="eyebrow">YOUR JOURNEY</div><h3>One step at a time.</h3><p>Your profile is <b>70%</b> complete. Add a credit to shine brighter.</p><button onClick={()=>{setTab('profile');notify('Let’s polish your profile!')}}>Complete profile <span>→</span></button></div><div className="section-title"><h3>People to meet</h3><button onClick={()=>setTab('network')}>See all</button></div>{people.map(p=><div className="person" key={p.name}><Avatar initials={p.avatar}/><div><strong>{p.name}</strong><span>{p.role} · {p.region}</span></div><button onClick={()=>notify(`Invitation sent to ${p.name}!`)}><Plus size={17}/></button></div>)}</aside></div>{toast&&<Toast text={toast}/>}</div>
}
function Onboarding({region,setRegion,role,setRole,name,setName,finish}) { const [step,setStep]=useState(0); return <div className="onboarding"><div className="film-grain"/><div className="onboard-nav"><div className="brand"><span className="brand-mark">✦</span><span>INDIAN <b>CINEMA</b></span></div><span className="step-count">0{step+1} / 03</span></div><div className="onboard-content">{step===0&&<><div className="hero-icon"><Film size={31}/></div><div className="eyebrow">WELCOME TO THE SET</div><h1>Where your next<br/><em>story</em> begins.</h1><p>A warm creative home for the people who bring Indian cinema to life. Find your crew, share your craft, and let’s make magic.</p><button className="primary big" onClick={()=>setStep(1)}>Step into the light <span>→</span></button></>}{step===1&&<><div className="eyebrow">TELL US YOUR CINEMA</div><h2>Which film world<br/>feels like home?</h2><div className="choice-grid">{regions.map(r=><button className={region===r?'selected':''} onClick={()=>setRegion(r)} key={r}><span className="radio"/>{r}<small>{r==='Bollywood'?'Hindi':r==='Tollywood'?'Telugu':r==='Kollywood'?'Tamil':r==='Mollywood'?'Malayalam':'Kannada'} cinema</small></button>)}</div><button className="primary" onClick={()=>setStep(2)}>That’s my scene <span>→</span></button></>}{step===2&&<><div className="eyebrow">YOUR CRAFT</div><h2>What do you bring<br/>to the frame?</h2><div className="role-wrap">{roles.map(r=><button className={role===r?'selected':''} onClick={()=>setRole(r)} key={r}>{r}</button>)}</div><label className="name-input"><span>Your name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="What should we call you?"/></label><button className="primary" onClick={finish}>Let’s make magic <Sparkles size={17}/></button></>}</div><div className="bulbs">{Array.from({length:18}).map((_,i)=><i key={i}/>)}</div></div> }
function Home({name,role,region,posts,composer,setComposer,publish,like,notify}) { return <><div className="welcome"><div><div className="eyebrow">THURSDAY, 24 SEPTEMBER 2026</div><h1>Lights, camera, <em>{name.split(' ')[0]}!</em></h1><p>Your creative circle is waiting for its next great story.</p></div><div className="streak"><span>✦</span><b>3 day</b><small>creative streak</small></div></div><div className="tabs"><button className="active">For you</button><button onClick={()=>notify('Region filters are ready for your next release!')}>{region} scene</button><button onClick={()=>notify('Role filters coming to your studio!')}>{role}s</button></div><div className="composer"><Avatar initials="AS"/><div><textarea value={composer} onChange={e=>setComposer(e.target.value)} placeholder="What’s happening on your set? Share a thought, a win, or a little inspiration..."/><div className="composer-foot"><span><Film size={16}/> Add to your story</span><button className="primary small" onClick={publish}>Post <Send size={14}/></button></div></div></div>{posts.map(p=><article className="post" key={p.id}><div className="post-head"><Avatar initials={p.avatar}/><div><strong>{p.name}</strong><span>{p.role} · {p.region} <i>·</i> {p.time}</span></div><button className="dots">•••</button></div><p className="post-copy">{p.content}</p><div className="post-stats"><span>{p.likes} appreciations</span><span>{p.comments} comments</span></div><div className="post-actions"><button className={p.liked?'liked':''} onClick={()=>like(p.id)}><Heart size={18} fill={p.liked?'currentColor':'none'}/> Appreciate</button><button onClick={()=>notify('Comments are a great way to start a conversation!')}><MessageCircle size={18}/> Comment</button><button onClick={()=>notify('Post ready to share with your circle!')}><Send size={17}/> Share</button></div></article>)}</> }
function Network({search,notify}) { const list=people.filter(p=>!search||`${p.name} ${p.role} ${p.region}`.toLowerCase().includes(search.toLowerCase())); return <><div className="page-heading"><div className="eyebrow">YOUR CREATIVE CIRCLE</div><h1>Meet your <em>people.</em></h1><p>Every great film starts with a great team.</p></div><div className="network-grid">{list.map(p=><div className="network-card" key={p.name}><Avatar initials={p.avatar} large/><h3>{p.name}</h3><span>{p.role}</span><small><MapPin size={13}/> {p.region}</small><button className="primary small" onClick={()=>notify(`Invitation sent to ${p.name}!`)}>Connect <Plus size={14}/></button></div>)}</div></> }
function Profile({name,role,region,notify}) { return <><div className="profile-hero"><div className="profile-cover"/><div className="profile-info"><Avatar initials="AS" large/><div><h1>{name}</h1><p>{role} · {region}</p><span><MapPin size={14}/> Mumbai, India</span></div><button className="primary" onClick={()=>notify('Profile editor is ready for your story!')}>Edit profile</button></div></div><div className="profile-columns"><section className="post"><div className="eyebrow">ABOUT THE ARTIST</div><h2>Making room for stories that stay with you.</h2><p className="muted">I believe every frame is an invitation — to feel, to wonder, and to see the world a little differently.</p></section><section className="post badges"><div className="eyebrow">ACHIEVEMENTS</div><div className="badge"><span>✦</span><div><b>First light</b><small>Joined the creative circle</small></div><Check size={16}/></div><div className="badge"><span>🎬</span><div><b>Profile complete</b><small>Tell the industry your story</small></div><Check size={16}/></div></section></div></> }
createRoot(document.getElementById('root')).render(<App />)
